server:
  port: 9204
  servlet:
    application-display-name: ruoyi-test
spring:
  profiles:
    active: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest@123
    virtual-host: /