server:
  port: 9001
  servlet:
    context-path: /
spring:
  profiles:
    active: dev
  rabbitmq:
    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息
    host: localhost
    port: 5672
    username: guest
    password: guest@123
    virtual-host: /mq-demo